name = "dead_jade_kingfisher-09e9"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "dead_jade_kingfisher-09e9_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "dead_jade_kingfisher-09e9.wasm"
command = "npm run build:release"
